### ISSUE TITLE
Fsbrowser

### ISSUE THREAD

**Issue by AiLe2611** [jeecrypt/JeeUI2#11]
Кто-нибудь пробовал прикрутить FSBrowser?

**Comment by ilyav3** [comment]
Кому-то, для начала, надо школу закончить.

**Comment by AiLe2611** [comment]
> 
> 
> Кому-то, для начала, надо школу закончить.

Если тебе так принципиально, то исправил...
PS: русский язык в школе не учил и живу не в России.
